### ISSUE TITLE
Gem changing model names

### ISSUE THREAD

**Issue by jordigg** [davidcelis/inflections#13]
Hi! Is this gem being maintained?

I've tried the gem, I wanted to contribute adding some more languages but when I try it seems that some of my models change their names. When I start the rails server I get:

"Inflections currently does not support your default_locale. Defaulting to English (en)."

And this is my default locale:
```rails
config.i18n.default_locale = :en
```

One of my models "CommentsController" becomes "CommentsesController" when using it in Spanish. Why is it affecting my models names? I though it was only being uses when calling ".pluralize".

When I remove the gem it works fine.

Thanks!

**Comment by davidcelis** [comment]
Hey! Sorry it’s taken me a while to respond. To answer your first question, I’m not sure why that warning would be getting output when your default_locale is already set to English. What version of Rails are you on, and what version of Inflections are you using? I don’t suppose you’d be able to show me your source code?

To answer your second question, the Inflector touches a lot of things. My gem doesn’t just affect methods on Strings; ActiveSupport uses the Inflector to infer table names, model names, controller names, and other things related to actual Constants.

**Comment by gagalago** [comment]
I am the same issue on model name. Is-it possible that it is your english inflection rules that produce that ?

**Comment by davidcelis** [comment]
What version of inflections have you ended up with, @gagalago? My guess is that my versioning scheme is just a mess and that you're on 0.0.5. Versioning alongside ActiveSupport was a dumb idea. I'm going to bump to 4.0.1 and get rid of the weird dependency stuff.

**Comment by davidcelis** [comment]
Can you please let me know if this still happens in 4.0.1? Any code would help too. I've generated test apps and things like `rails g scaffold Comment body:text` works as expected and pluralizes to Comments. "Comments" would definitely pluralize to "Commentses" but there's no reason that "Comments" should be getting pluralized unless Rails is pluralizing things that have already _been_ pluralized...

**Comment by gagalago** [comment]
I have try the last 4.0.1 version and the same problem apear. 

But if i copy/past only the french inflection from your gem in a initializer, I haven't errors. It is why i have some suspection about your english inflection. Why your inflection is different from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb ?

**Comment by davidcelis** [comment]
> Why your inflection is different from https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb ?

From the README:

> This gem's purpose is twofold: to remove the cruft from ActiveSupport's inflections and provide a more sane set of defaults for Ruby/Rails applications in English while also providing default rules for other languages.

**Comment by davidcpell** [comment]
I am also getting `Inflections currently does not support your default_locale. Defaulting to English (en).` despite not having changed the `config.i18n.default_locale` in `application.rb` (default is `:en`). 

My Rails version is 4.1.4 with Inflections 0.0.5

**Comment by davidcelis** [comment]
@davidcpell can you `bundle update inflections`? I removed version constraints that should be making that happen

**Comment by davidcpell** [comment]
@davidcelis that took care of it. thank you!

**Comment by davidcelis** [comment]
@gagalago @jordigg my guess is that words already pluralized are frequently passed to `pluralize` causing a double pluralization. Many of ActiveSupport's default rules and exceptions account for double pluralization and end up not modifying the word further. Maybe re-defining the english set is a futile effort considering how much of the framework relies on their flawed system of singularization/pluralization

**Comment by davidcelis** [comment]
It's done. I give up. You win, Rails! :disappointed:
